name: build r6300v2-master


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
#  branches: 
#    - master
  schedule:
    - cron: 0 8 * * 5
  watch:
    types: [started]
    


jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      uses: actions/checkout@v2
      # Runs a single command using the runners shell
    - name: Update && install packages
      run: |
        sudo dpkg-reconfigure dash
        sudo apt update
        sudo apt-get install libtool-bin cmake libproxy-dev uuid-dev liblzo2-dev autoconf automake-1.15 bash bison \
        bzip2 diffutils file flex m4 g++ gawk groff-base libncurses5-dev libtool libslang2 make patch perl pkg-config shtool \
        subversion tar texinfo zlib1g zlib1g-dev git gettext libexpat1-dev libssl-dev cvs gperf unzip \
        python libxml-parser-perl gcc-multilib gconf-editor libxml2-dev g++-multilib gitk libncurses5 mtd-utils \
        libncurses5-dev libvorbis-dev git autopoint autogen sed build-essential intltool libglib2.0-dev \
        xutils-dev lib32z1-dev xsltproc gtk-doc-tools
       
    # Runs a set of commands using the runners shell
    - name: Update x86 package
      run: |
        sudo dpkg --add-architecture i386
        sudo dpkg --print-foreign-architectures
        sudo apt-get update
        sudo apt-get install -y libc6-i386 lib32stdc++6 lib32z1 libelf1:i386 libc6-dev-i386
        
    - name: Clone source code
      run: |       
        #git clone --branch 384.19-beta1 https://github.com/RMerl/asuswrt-merlin.ng
        #git clone --branch 384.19-beta1-mainline https://github.com/RMerl/asuswrt-merlin.ng
        #git clone --branch 384.18-mainline https://github.com/RMerl/asuswrt-merlin.ng
        git clone --branch 384.18 https://github.com/RMerl/asuswrt-merlin.ng
        git clone https://github.com/RMerl/am-toolchains.git
        git clone https://github.com/izrt/r6300-merlin.ng.git
                
        sudo mkdir -p /media/asuswrt/
        sudo mkdir -p /opt/images/
                
    - name: Link Directory
      run: |
        sudo ln -s $(pwd)/am-toolchains/brcm-arm-hnd /opt/toolchains
        sudo ln -s $(pwd)/am-toolchains/brcm-arm-sdk/hndtools-arm-linux-2.6.36-uclibc-4.5.3 /opt/brcm-arm
        ln -s $(pwd)/am-toolchains/brcm-arm-sdk  $(pwd)/asuswrt-merlin.ng/release/src-rt-6.x.4708/toolchains
        
        sudo ln -sf bash /bin/sh
        
        echo "export LD_LIBRARY_PATH=$LD_LIBRARY:/opt/toolchains/crosstools-arm-gcc-5.3-linux-4.1-glibc-2.22-binutils-2.25/usr/lib" >> ~/.profile
        echo "export TOOLCHAIN_BASE=/opt/toolchains" >> ~/.profile
        echo "PATH=\$PATH:/opt/toolchains/crosstools-arm-gcc-5.3-linux-4.1-glibc-2.22-binutils-2.25/usr/bin" >> ~/.profile
        echo "PATH=\$PATH:/opt/toolchains/crosstools-aarch64-gcc-5.3-linux-4.1-glibc-2.22-binutils-2.25/usr/bin" >> ~/.profile
        
        echo "export LD_LIBRARY_PATH=$LD_LIBRARY:/opt/toolchains/crosstools-arm-gcc-5.5-linux-4.1-glibc-2.26-binutils-2.28.1/usr/lib" >> ~/.profile
        echo "PATH=\$PATH:/opt/toolchains/crosstools-arm-gcc-5.5-linux-4.1-glibc-2.26-binutils-2.28.1/usr/bin" >> ~/.profile
        echo "PATH=\$PATH:/opt/toolchains/crosstools-aarch64-gcc-5.5-linux-4.1-glibc-2.26-binutils-2.28.1/usr/bin" >> ~/.profile
        
        echo "PATH=\$PATH:/opt/brcm-arm/bin" >> ~/.profile 
        
        sudo ln -s $(pwd)/asuswrt-merlin.ng /media/asuswrt/asuswrt-merlin.ng       
        cd /media/asuswrt/asuswrt-merlin.ng
        
        echo "::set-env name=MERLIN_VERSION::$(git show-ref --heads -s)"
        echo "::set-env name=MERLIN_TAG::$(git show-ref --heads --hash=8)"
        echo "::set-env name=BUILD_DATE::$(date +%Y%m%d%H%M)"
        
    - name: Modify File
      run: |  
       
       cp -rf $(pwd)/r6300-merlin.ng/release/src/router/rc/sysdeps/init-broadcom.c  /media/asuswrt/asuswrt-merlin.ng/release/src/router/rc/sysdeps/
    - name: Build Firmware
      run: |
        export PATH=$PATH:/opt/brcm-arm/bin
        
        cd  /media/asuswrt/asuswrt-merlin.ng/release/src-rt
        echo "add tag to version"
        sed -i 's/EXTENDNO=.*/&_${{ env.MERLIN_TAG }}/g' version.conf
        
        cd /media/asuswrt/asuswrt-merlin.ng/release/src-rt-6.x.4708
        make clean
        make rt-ac68u
        echo "build image done"     
        
        #cd /media/asuswrt/asuswrt-merlin.ng/release/src-rt-6.x.4708/cfe/
        #make
        #echo "build cfe done"
        
#    - name : Upload packages
#      uses: actions/upload-artifact@master
#      if: always()
#      with:
#      name: Padavan-packages
#      path: /opt/images
    - name: Move file && Checksum
      run: |
        sudo mv -f /media/asuswrt/asuswrt-merlin.ng/release/src-rt-6.x.4708/image/*.trx /opt/images/
        sudo cp /media/asuswrt/asuswrt-merlin.ng/release/src-rt-6.x.4708/cfe/cfe*.bin /opt/images/
        sudo cp /media/asuswrt/asuswrt-merlin.ng/release/src-rt/version.conf /opt/images/
        
        sha256sum /opt/images/* > /opt/images/checksum.txt
        
    - name: Create Release
      id: create_release
      uses: ncipollo/release-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        artifacts: "/opt/images/*.*"
        allowUpdates: true 
        commit: master 
        tag: ${{ env.BUILD_DATE }}_master_R6300V2_iZRT_${{ env.MERLIN_TAG }}
        body: |
          this is only a latest build from master
          version: https://github.com/RMerl/asuswrt-merlin.ng/${{ env.MERLIN_VERSION }}
        token: ${{ secrets.GITHUB_TOKEN }}
        draft: false
        prerelease: false
